Fixed post vars
t3kit/t3kit_extension_tools pull request #15
Opened 2017-01-25 14:43 UTC by anjeylink

https://github.com/t3kit/t3kit/issues/92

2017-01-27 09:40 UTC, MattiasNilsson commented
Looks good, just some smaller adjustments needed.

2017-01-27 09:40 UTC, MattiasNilsson commented on Classes/Hook/DataHandlerHook.php
> +     * If ab child page was created save its uid
ab should be a

2017-01-27 09:40 UTC, MattiasNilsson commented on ext_emconf.php
>  			'typo3'  => '7.5.0-7.6.99',
Is this right dependency?

2017-01-27 09:40 UTC, MattiasNilsson commented on Classes/Utility/HelperUtility.php
> +            self::$extConf = @unserialize((string)$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['t3kit_extension_tools']);
Why is this suppressed?

2017-01-27 09:51 UTC, anjeylink commented
i fixed wrong comment and suppression of "unserialize". about dependency, shall we update it to typo3 8  ?

2017-02-09 15:09 UTC, dmh commented
@jozefspisiak or @MattiasNilsson

2017-02-10 09:41 UTC, MattiasNilsson requested changes
This looks good, just some smaller adjustments. This PR should also be marked as breaking change because of the new database column.

2017-02-10 09:41 UTC, MattiasNilsson commented on Classes/Utility/HelperUtility.php
> +            self::$extConf = unserialize((string)$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['t3kit_extension_tools']);
Check that this is set before doing unserialize: $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['t3kit_extension_tools']

2017-02-10 09:41 UTC, MattiasNilsson commented on ext_conf_template.txt
> +additionalChars =
Please use full naming: additionalCharacters

2017-02-10 09:41 UTC, MattiasNilsson commented on ext_conf_template.txt
> +fixedPostVarsConfFile = typo3conf/ext/t3kit_extension_tools/Configuration/Realurl/predefined_fixedPostVars_conf.php
fixedPostVarsConfFile => fixedPostVarsConfigurationfFile

2017-02-10 09:41 UTC, MattiasNilsson commented on ext_localconf.php
> +    # Register data handler hook
Replace the usage of # comment to // instead so we all use the same syntax.

2017-02-15 20:31 UTC, MattiasNilsson commented
Ping @anjeylink

2017-02-16 08:15 UTC, MattiasNilsson commented
Nice!

2017-02-16 08:15 UTC, merged